desc state;
desc district;
desc block;
desc centre;
desc party;
desc voter;
desc candidate;
desc employee;
desc security;
desc election;
desc vote_count;
desc result;

insert into STATE values('WB', 'WEST BENGAL');
insert into STATE values('MH', 'MAHARASTRA');
insert into STATE values('BR', 'BIHAR');
insert into STATE values('GJ', 'GUJRAT');
insert into STATE values('AM', 'ASSAM');
insert into STATE values('JH', 'JHARKHAND');
insert into STATE values('TN', 'TAMIL NADU');
insert into STATE values('DL', 'DELHI');
SELECT * FROM STATE;

INSERT ALL
INTO DISTRICT VALUES ('WB1','WB','KOLKATA')
INTO DISTRICT VALUES ('WB2','WB','BURDWAN')
INTO DISTRICT VALUES ('WB3','WB','SOUTH 24 PARGANAS')
INTO DISTRICT VALUES ('WB4','WB','NORTH 24 PARGANAS')
INTO DISTRICT VALUES ('WB5','WB','NADIA')
INTO DISTRICT VALUES ('WB6','WB','BIRBHUM')
INTO DISTRICT VALUES ('WB7','WB','HOOGHLY')
INTO DISTRICT VALUES ('WB8','WB','MURSHIDABAD')
SELECT * FROM DUAL;

SELECT * FROM DISTRICT;

INSERT ALL
INTO BLOCK VALUES ('WB2_1','WB2','BARRDHAMAN')
INTO BLOCK VALUES ('WB2_2','WB2','ASANSOL')
INTO BLOCK VALUES ('WB2_3','WB2','DURGAPUR')
INTO BLOCK VALUES ('WB2_4','WB2','RANIGANJ')
INTO BLOCK VALUES ('WB2_5','WB2','KATWA')
SELECT * FROM DUAL;

SELECT * FROM BLOCK;

SELECT * FROM BLOCK WHERE DISTRICT_ID = ( SELECT DISTRICT_ID FROM DISTRICT WHERE DISTRICT_NAME = 'BURDWAN');

INSERT ALL
INTO CENTRE VALUES ('BAR_1','WB2_1','F.P SCHOOL','G.T ROAD BURDWAN')
INTO CENTRE VALUES ('BAR_2','WB2_1','L.P SCHOOL','SUBODH PALLY BURDWAN')
INTO CENTRE VALUES ('ASA_1','WB2_2','ASANSOL RAIL SCHOOL','RAILWAY STATION ASANSOL')
INTO CENTRE VALUES ('ASA_2','WB2_2','ASANSOL CITY CENTRE','CITY CENTRE MARKET')
INTO CENTRE VALUES ('KAT_1','WB2_5','KATWA K.D.I','D.B ROAD, KATWA')
SELECT * FROM DUAL;

SELECT * FROM CENTRE;


Drop Table Candidate
Drop Table Vote_Count
Drop Table Result
Drop Table Election


ALTER TABLE Party
DROP PRIMARY KEY

ALTER TABLE PARTY
MODIFY PARTY_NAME VARCHAR(50);

INSERT ALL
INTO PARTY VALUES ('TMC','TRINOMOOL CONGRESS','GRASS')
INTO PARTY VALUES ('BJP','BHARITIYA JANATA PARTY','LOTUS')
INTO PARTY VALUES ('CPM','CPM','HAMMER)
SELECT * FROM DUAL;


CREATE TABLE CANDIDATE (CANDIDATE_ID VARCHAR(10), VOTER_ID VARCHAR(10), PARTY_ID VARCHAR(5), BLOCK_ID VARCHAR(5), PRIMARY KEY (CANDIDATE_ID), FOREIGN KEY (VOTER_ID) REFERENCES VOTER (VOTER_ID), FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID), FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK (BLOCK_ID));



INSERT ALL
INTO PARTY VALUES ('TMC','WB2_1','TRINOMOOL CONGRESS','GRASS')
INTO PARTY VALUES ('TMC','WB2_2','TRINOMOOL CONGRESS','GRASS')
INTO PARTY VALUES ('TMC','WB2_3','TRINOMOOL CONGRESS','GRASS')
INTO PARTY VALUES ('TMC','WB2_4','TRINOMOOL CONGRESS','GRASS')
INTO PARTY VALUES ('TMC','WB2_5','TRINOMOOL CONGRESS','GRASS')
INTO PARTY VALUES ('BJP','WB2_1','BHARITIYA JANATA PARTY','LOTUS')
INTO PARTY VALUES ('BJP','WB2_2','BHARITIYA JANATA PARTY','LOTUS')
INTO PARTY VALUES ('BJP','WB2_3','BHARITIYA JANATA PARTY','LOTUS')
INTO PARTY VALUES ('BJP','WB2_4','BHARITIYA JANATA PARTY','LOTUS')
INTO PARTY VALUES ('BJP','WB2_5','BHARITIYA JANATA PARTY','LOTUS')
SELECT * FROM DUAL;

DROP TABLE PARTY;



CREATE TABLE PARTY (PARTY_ID VARCHAR(5), PARTY_NAME VARCHAR(20), PARTY_SYMBOL VARCHAR(20), PRIMARY KEY (PARTY_ID));
CREATE TABLE PARTY_LOCATION (PARTY_ID VARCHAR(5),BLOCK_ID VARCHAR(10) , FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID), FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK(BLOCK_ID));


DROP TABLE PARTY_LOCATION
INSERT INTO PARTY VALUES('TMC','TRINOMUL CONGRESS','GRASS');
INSERT INTO PARTY VALUES('CPM','CPM','HAMMER');
INSERT INTO PARTY VALUES('BJP','BHARAT JANATA PARTY','LOTUS');

DESC PARTY_LOCATION;
SELECT * FROM BLOCK
INSERT ALL
INTO PARTY_LOCATION VALUES ('TMC','WB2_1')
INTO PARTY_LOCATION VALUES ('TMC','WB2_2')
INTO PARTY_LOCATION VALUES ('TMC','WB2_3')
INTO PARTY_LOCATION VALUES ('CPM','WB2_1')
SELECT * FROM DUAL;

DESC PARTY_LOCATION;

SELECT * FROM PARTY_LOCATION;


CREATE TABLE CANDIDATE (CANDIDATE_ID VARCHAR(10), VOTER_ID VARCHAR(10), PARTY_ID VARCHAR(5), BLOCK_ID VARCHAR(5), PRIMARY KEY (CANDIDATE_ID), FOREIGN KEY (VOTER_ID) REFERENCES VOTER (VOTER_ID), FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID), FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK (BLOCK_ID));

SELECT * FROM CANDIDATE;

INSERT ALL
INTO VOTER VALUES ('WBVOTER1','BAR_1','SOUMEET AHMED','11-NOV-95','MISABUL AHMED','BURDWAN')
INTO VOTER VALUES ('WBVOTER2','BAR_2','GOLOK HAS','12-NOV-95','NILESH HAS','BURDWAN')
INTO VOTER VALUES ('WBVOTER3','BAR_1','FAIZAN JAN','2-NOV-95','AMMAA JAN','BURDWAN')
INTO VOTER VALUES ('WBVOTER4','BAR_2','RITESH ROY','19-NOV-95','SOMESH ROY','BURDWAN')
INTO VOTER VALUES ('WBVOTER5','ASA_1','MITHUN WARDEN','23-NOV-95','CHANDAN WARDEN','ASANSOL')
INTO VOTER VALUES ('WBVOTER6','KAT_1','BIPASA ROY','1-JAN-95','AJIT ROY','KATWA')
INTO VOTER VALUES ('WBVOTER7','KAT_1','ROHAN MONDAL','11-JUL-95','SOURAV MONDAL','KATWA')
SELECT * FROM DUAL;

SELECT * FROM VOTER;

INSERT ALL
INTO CANDIDATE VALUES ('WBCAN1','WBVOTER1','TMC','WB2_1')
INTO CANDIDATE VALUES ('WBCAN2','WBVOTER2','TMC','WB2_2')
INTO CANDIDATE VALUES ('WBCAN3','WBVOTER3','TMC','WB2_3')
INTO CANDIDATE VALUES ('WBCAN4','WBVOTER4','BJP','WB2_1')
INTO CANDIDATE VALUES ('WBCAN5','WBVOTER5','BJP','WB2_2')
INTO CANDIDATE VALUES ('WBCAN6','WBVOTER6','BJP','WB2_3')
SELECT * FROM DUAL;

SELECT * FROM CANDIDATE;


CREATE TABLE ELECTION (ELECTION_ID VARCHAR(5), DISTRICT_ID VARCHAR(5), ELECTION_DATE DATE, PRIMARY KEY (ELECTION_ID), FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICT(DISTRICT_ID));


CREATE TABLE VOTE_COUNT (ELECTION_ID VARCHAR(5), CENTRE_ID VARCHAR(5), PARTY_ID VARCHAR(5), TOTAL_VOTE NUMBER, FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION (ELECTION_ID), FOREIGN KEY (CENTRE_ID) REFERENCES CENTRE(CENTRE_ID), FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID));


CREATE TABLE RESULT (ELECTION_ID VARCHAR(5), CENTRE_ID VARCHAR(5), PARTY_ID VARCHAR(5), FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION (ELECTION_ID), FOREIGN KEY (CENTRE_ID) REFERENCES CENTRE (CENTRE_ID), FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID));

SELECT VOTER_NAME FROM VOTER V, CANDIDATE C, PARTY P, BLOCK B WHERE 
V.VOTER_ID = C.VOTER_ID 
AND C.PARTY_ID = P.PARTY_ID
AND C.BLOCK_ID = B.BLOCK_ID
AND P.PARTY_ID = 'BJP'
AND B.BLOCK_NAME = 'ASANSOL';


