INSERT ALL
INTO DISTRICT VALUES ('WB9','WB','Bankura')
INTO DISTRICT VALUES ('WB10','WB','Cooch Behar')
INTO DISTRICT VALUES ('WB11','WB','Darjeeling')
INTO DISTRICT VALUES ('WB12','WB','East Midnapore')
INTO DISTRICT VALUES ('WB13','WB','Howrah')
INTO DISTRICT VALUES ('WB14','WB','Jalpaiguri')
INTO DISTRICT VALUES ('WB15','WB','Malda')
INTO DISTRICT VALUES ('WB16','WB','Purulia')
INTO DISTRICT VALUES ('WB17','WB','West Midnapore')
SELECT * FROM DUAL;

INSERT ALL
SELECT * FROM DUAL;

INSERT ALL
INTO BLOCK VALUES ('WB3_1','WB3','Baruipur')
INTO BLOCK VALUES ('WB3_2','WB3','Canning')
INTO BLOCK VALUES ('WB3_3','WB3','Diamond Harbour')
INTO BLOCK VALUES ('WB3_4','WB3','Kakdwip')
INTO BLOCK VALUES ('WB3_5','WB3','Alipore Sadar')
INTO BLOCK VALUES ('WB4_1','WB4','Barrackpore')
INTO BLOCK VALUES ('WB4_2','WB4','Barasat Sadar')
INTO BLOCK VALUES ('WB4_3','WB4','Bangaon')
INTO BLOCK VALUES ('WB4_4','WB4','Basirhat')
INTO BLOCK VALUES ('WB4_5','WB4','Bidhannagar')
INTO BLOCK VALUES ('WB5_1','WB5','Krishnanagar Sadar')
INTO BLOCK VALUES ('WB5_2','WB5','Kalyani')
INTO BLOCK VALUES ('WB5_3','WB5','Ranaghat')
INTO BLOCK VALUES ('WB5_4','WB5','Tehatta')
INTO BLOCK VALUES ('WB6_1','WB6','Suri Sadar')
INTO BLOCK VALUES ('WB6_2','WB6','Bolpur')
INTO BLOCK VALUES ('WB6_3','WB6','Rampurhat')
INTO BLOCK VALUES ('WB7_1','WB7','Chinsurah')
INTO BLOCK VALUES ('WB7_2','WB7','Chandannagore')
INTO BLOCK VALUES ('WB7_3','WB7','Srirampore')
INTO BLOCK VALUES ('WB7_4','WB7','Arambagh')
INTO BLOCK VALUES ('WB8_1','WB8','Barhampur')
INTO BLOCK VALUES ('WB8_2','WB8','Domkol')
INTO BLOCK VALUES ('WB8_3','WB8','Lalbag')
INTO BLOCK VALUES ('WB8_4','WB8','Kandi')
INTO BLOCK VALUES ('WB8_5','WB8','Jangipur')
INTO BLOCK VALUES ('WB9_1','WB9','Bankura Sadar')
INTO BLOCK VALUES ('WB9_2','WB9','Khatra')
INTO BLOCK VALUES ('WB9_3','WB9','Bishnupur')
INTO BLOCK VALUES ('WB10_1','WB10','Cooch Behar Sadar')
INTO BLOCK VALUES ('WB10_2','WB10','Dinhata')
INTO BLOCK VALUES ('WB10_3','WB10','Mathabhanga')
INTO BLOCK VALUES ('WB10_4','WB10','Tufanganj')
INTO BLOCK VALUES ('WB11_1','WB11','Darjeeling Sadar')
INTO BLOCK VALUES ('WB11_2','WB11','Kalimpong')
INTO BLOCK VALUES ('WB11_3','WB11','Kurseong')
INTO BLOCK VALUES ('WB11_4','WB11','Siliguri')
INTO BLOCK VALUES ('WB12_1','WB12','Tamluk')
INTO BLOCK VALUES ('WB12_2','WB12','Haldia')
INTO BLOCK VALUES ('WB12_3','WB12','Egra')
INTO BLOCK VALUES ('WB12_4','WB12','Contai')
INTO BLOCK VALUES ('WB13_1','WB13','Howrah Sadar')
INTO BLOCK VALUES ('WB13_2','WB13','Uluberia')
INTO BLOCK VALUES ('WB14_1','WB14','Jalpaiguri Sadar')
INTO BLOCK VALUES ('WB14_2','WB14','Malbazar')
INTO BLOCK VALUES ('WB15_1','WB15','Chanchal')
INTO BLOCK VALUES ('WB15_2','WB15','Malda Sadar')
INTO BLOCK VALUES ('WB16_1','WB16','Purulia Sadar East')
INTO BLOCK VALUES ('WB16_2','WB16','Purulia Sadar West')
INTO BLOCK VALUES ('WB16_3','WB16','Raghunathpur')
INTO BLOCK VALUES ('WB17_1','WB17','Kharagpur')
INTO BLOCK VALUES ('WB17_2','WB17','Medinipur Sadar')
INTO BLOCK VALUES ('WB17_3','WB17','Ghatal')
INTO BLOCK VALUES ('WB17_4','WB17','Jhargram')
SELECT * FROM DUAL;

ALTER TABLE BLOCK MODIFY BLOCK_ID VARCHAR(10);
SELECT * FROM BLOCK;
SELECT * FROM CENTRE;
SELECT * FROM VOTER;

INSERT ALL
INTO CENTRE VALUES ('DUR_1','WB2_3','Durgapur Ispat Vidyalaya','MIRABAI ROAD, DURGAPUR')
INTO CENTRE VALUES ('DUR_2','WB2_3','Durgapur Sosaiti Ab Edukeshanal Myanejament','TANSEN ROAD, DURGAPUR')
INTO CENTRE VALUES ('RAN_1','WB2_3','Kadam Danga FPSchool','A J Road, Ranijang')
INTO CENTRE VALUES ('RAN_2','WB2_3','Ranai F P School','K J Road, Ranijang')
INTO CENTRE VALUES ('DIH_1','WB3_3','Nila Aadarsh Junior Basic School','Nila, Diamond Harbour')
INTO CENTRE VALUES ('DIH_2','WB3_3','Noorpur Thakur Anukul Chandra High School','Noorpur, Diamond Harbour')
INTO CENTRE VALUES ('KAK_1','WB3_4','Ramtanunagar High Madrasa','Ramtanunagar, Kakdwip')
INTO CENTRE VALUES ('KAK_2','WB3_4','Lakshmipur F.P. School','Lakshmipur, Kakdwip')
INTO CENTRE VALUES ('BRU_1','WB3_1','Meliya Raicharan Bidyapith','P L Road, Baruipur')
INTO CENTRE VALUES ('BRU_2','WB3_1','Bhanta Bahirampur J.B School','Bhatna, Baruipur')
INTO CENTRE VALUES ('BRA_1','WB4_1','Sankhabanik Prathamik Vidyalaya','MN Road, Barrackpore')
INTO CENTRE VALUES ('BRA_2','WB4_1','Niranjan Nagar Vidyapith','Niranjan Nagar, Barrackpore')
INTO CENTRE VALUES ('BA_1','WB4_2','Matangini Shishu Shiksha Kendra','Kulberia, Barasat')
INTO CENTRE VALUES ('BA_2','WB4_2','Chhoto Jaguliya High School','Chhoto Jaguliya, Barasat')
INTO CENTRE VALUES ('KL_1','WB5_2','Raninagar Gopalachandr Prathamik Vidyalaya','Raninagar, Kalyani')
INTO CENTRE VALUES ('KL_2','WB5_2','Charjirat Prathamik Vidyalaya','Charjirat, Kalyani')
INTO CENTRE VALUES ('TEH_1','WB5_4','Fazilnagar High School','Fazilnagar, Tehatta')
INTO CENTRE VALUES ('TEH_2','WB5_4','Piarpur Primary School','Piarpur, Tehatta')
INTO CENTRE VALUES ('BOL_1','WB6_2','Batikar Abhedananda School','Batikor, Bolpur')
INTO CENTRE VALUES ('BOL_2','WB6_2','Balta Prathamik Vidyalaya','Balta, Bolpur')
INTO CENTRE VALUES ('RAM_1','WB6_3','Paikpara Prathamik Vidyalaya','Khedamara, Rampurhat')
INTO CENTRE VALUES ('RAM_2','WB6_3','Shalbuni Prathamik Vidyalaya','Ekpara, Rampurhat')
INTO CENTRE VALUES ('BIS_1','WB9_3','Baidhya Prathamik Vidyalaya','Bhagaband, Bishnupur')
INTO CENTRE VALUES ('BIS_2','WB9_3','Dapanajudi Prathamik Vidyalaya','Bendara, Bishnupur')
INTO CENTRE VALUES ('DAR_1','WB11_1','Sirikhola Primary School','Singalila Forest, Darjeeling')
INTO CENTRE VALUES ('DAR_2','WB11_1','Rimbick Junior Basic School','Rimbick, Darjeeling')
INTO CENTRE VALUES ('KAL_1','WB11_2','Pranami Balika Vidya Mandir','10th Mile, Kalimpong')
INTO CENTRE VALUES ('KAL_2','WB11_2','St.Augustines School','8th Mile, Kalimpong')
SELECT * FROM DUAL;

ALTER TABLE CENTRE MODIFY CENTRE_NAME VARCHAR(50);
ALTER TABLE CENTRE MODIFY BLOCK_ID VARCHAR(10);

INSERT ALL
INTO VOTER VALUES ('WB_V1','BAR_1','SOUMEET AHMED','11-NOV-95','MISABUL AHMED','BURDWAN')
INTO VOTER VALUES ('WB_V2','BAR_2','GOLOK HAS','12-DEC-95','NILESH HAS','BURDWAN')
INTO VOTER VALUES ('WB_V3','BAR_1','FAIZAN JAN','2-JAN-95','AMMAA JAN','BURDWAN')
INTO VOTER VALUES ('WB_V4','BAR_2','RITESH ROY','19-NOV-95','SOMESH ROY','BURDWAN')
INTO VOTER VALUES ('WB_V5','ASA_1','MITHUN WARDEN','23-MAR-95','CHANDAN WARDEN','ASANSOL')
INTO VOTER VALUES ('WB_V6','KAT_1','BIPASA ROY','1-JAN-95','AJIT ROY','KATWA')
INTO VOTER VALUES ('WB_V7','KAT_1','ROHAN MONDAL','11-JUL-95','SOURAV MONDAL','KATWA')
INTO VOTER VALUES ('WB_V8','DAR_1','ARIJIT SINGH','11-AUG-95','ADITYA SINGH','DARJEELING')
INTO VOTER VALUES ('WB_V9','KL_1','AJIT YADAV','12-JUL-94','LALU YADAV','KALYANI')
INTO VOTER VALUES ('WB_V10','DAR_2','ROHIT SHARMA','10-AUG-96','SOHAM SHARMA','DARJEELING')
INTO VOTER VALUES ('WB_V11','DIH_1','PAPPU JADHAV','21-JUL-97','VIVEK JADHAV','DIAMOND HARBOUR')
INTO VOTER VALUES ('WB_V12','KAL_1','BOBBY JASOOS','15-MAY-95','SOBBY JASOOS','KALIMPONG')
INTO VOTER VALUES ('WB_V13','KAK_1','SIMPA SHARMA','11-JUN-94','SAURABH SHARMA','KAKDWIP')
INTO VOTER VALUES ('WB_V14','TEH_1','SWETA MISHRA','17-JUL-95','AMIT MISHRA','TEHHATA')
INTO VOTER VALUES ('WB_V15','BOL_2','TONY SINGH','17-APR-95','JOHNNY SINGH','BOLPUR')
INTO VOTER VALUES ('WB_V16','BOL_1','DEBARATI GHATAK','27-JUL-95','ARGHYA GHATAK','BOLPUR')
INTO VOTER VALUES ('WB_V17','KAK_2','SUNNY KUMAR','12-NOV-95','MONU KUMAR','KAKDWIP')
INTO VOTER VALUES ('WB_V18','RAM_1','DEEPA KUMARI','17-DEC-95','SANJAY KUMAR','RAMPURHAT')
INTO VOTER VALUES ('WB_V19','BRA_1','SANJANA JAISWAL','17-JUL-95','PRITAM JAISWAL','BARRACKPUR')
INTO VOTER VALUES ('WB_V20','BIS_2','SHAHEEN AKHTAR','17-FEB-95','SHOAIB AKHTAR','BISHNUPUR')
SELECT * FROM DUAL;

SELECT * FROM VOTER;
SELECT * FROM CANDIDATE;

DELETE FROM CANDIDATE;
DELETE FROM VOTER;

INSERT ALL
INTO CANDIDATE VALUES ('WB_C1','WB_V1','TMC','WB2_1')
INTO CANDIDATE VALUES ('WB_C2','WB_V2','TMC','WB2_2')
INTO CANDIDATE VALUES ('WB_C3','WB_V3','TMC','WB2_3')
INTO CANDIDATE VALUES ('WB_C4','WB_V4','BJP','WB2_1')
INTO CANDIDATE VALUES ('WB_C5','WB_V5','BJP','WB2_2')
INTO CANDIDATE VALUES ('WB_C6','WB_V6','BJP','WB2_3')
SELECT * FROM DUAL;

SELECT *  FROM PARTY;
DELETE FROM PARTY_LOCATION;
DROP TABLE PARTY_LOCATION;
DESC PARTY_LOCATION;

INSERT ALL
INTO EMPLOYEE VALUES ('EMP_1', 'KAK_1', 'ARIJIT CHAKRABORTY', 'AK LANE,SILIGURI')
INTO EMPLOYEE VALUES ('EMP_2', 'BAR_1', 'FAIZAN AHMED', 'MG ROAD,KALIMPONG')
INTO EMPLOYEE VALUES ('EMP_3', 'KAK_2', 'ATIN TIWARI', 'RT ROAD,KURSEONG')
INTO EMPLOYEE VALUES ('EMP_4', 'BAR_2', 'ABHIJEET TALUDHAR', 'GT STREET,DARJEELING')
INTO EMPLOYEE VALUES ('EMP_5', 'DUR_1', 'PRITAM SADHU', 'SE ROAD,KATWA')
INTO EMPLOYEE VALUES ('EMP_6', 'RAN_1', 'SHIBRAJ KAR', 'MADHU PARK,KALYANI')
INTO EMPLOYEE VALUES ('EMP_7', 'ASA_1', 'SOUMEET BASAK', 'AJC BOSE ROAD,ASANSOL')
INTO EMPLOYEE VALUES ('EMP_8', 'ASA_2', 'SIMPA BASAK', 'SB ROAD,ASANSOL')
INTO EMPLOYEE VALUES ('EMP_9', 'DIH_1', 'KUSHAL BASU', 'AHRAMPARA,SARISHA')
INTO EMPLOYEE VALUES ('EMP_10', 'KL_1', 'AYAN CHATTERJEE', 'CSE PARA,JANA GATE')
INTO EMPLOYEE VALUES ('EMP_11', 'KL_2', 'JAJAJ ALAM', 'HT LANE,MURSHIDABAD')
INTO EMPLOYEE VALUES ('EMP_12', 'TEH_1', 'GOPAL VYAS', 'KLPARA,GIRISH PARK')
INTO EMPLOYEE VALUES ('EMP_13', 'TEH_2', 'RAKSHITA VYAS', 'TNU ROAD,MINTO PARK')
INTO EMPLOYEE VALUES ('EMP_14', 'BOL_1', 'ARUNDHUTI DUTTA', 'ITME LANE,PARK STREET')
INTO EMPLOYEE VALUES ('EMP_15', 'BOL_2', 'SHARMISTHA MISHRA', 'NITM ROAD,BEHALA')
INTO EMPLOYEE VALUES ('EMP_16', 'RAM_1', 'SANJANA KUMARI', 'BT PARA,SILPARA')
SELECT * FROM DUAL;

ALTER TABLE EMPLOYEE MODIFY EMPLOYEE_ID VARCHAR(10);


INSERT ALL 
INTO EMPLOYEE VALUES ('SEC_1', 'KAK_1', 'AYAN CHATTERJEE', 'BLACK CATS')
INTO EMPLOYEE VALUES ('SEC_2', 'BAR_1', 'EDWARD ELRIC', 'GORKHA REGIMENT')
INTO EMPLOYEE VALUES ('SEC_3', 'KAK_2', 'ALPHONSE ELRIC', '33 CORPS')
INTO EMPLOYEE VALUES ('SEC_4', 'BAR_2', 'ROY MUSTANG', 'Z PLUS')
INTO EMPLOYEE VALUES ('SEC_5', 'DUR_1', 'SOUMEET SADHU', 'BLACK CATS')
INTO EMPLOYEE VALUES ('SEC_6', 'RAN_1', 'ARIJIT KAR', 'GORKHA REGIMENT')
INTO EMPLOYEE VALUES ('SEC_7', 'ASA_1', 'PRITAM BASAK', 'GORKHA REGIMENT')
INTO EMPLOYEE VALUES ('SEC_8', 'ASA_2', 'PRANAV RAI', 'Z PLUS')
INTO EMPLOYEE VALUES ('SEC_9', 'DIH_1', 'SAYAN BASU', '33 CORPS')
INTO EMPLOYEE VALUES ('SEC_10', 'KL_1', 'GOPAL CHATTERJEE', 'BLACK CATS')
INTO EMPLOYEE VALUES ('SEC_11', 'KL_2', 'FAIZAN ALAM', 'GORKHA REGIMENT')
INTO EMPLOYEE VALUES ('SEC_12', 'TEH_1', 'ANDREW VYAS', '407 REGIMENT')
INTO EMPLOYEE VALUES ('SEC_13', 'TEH_2', 'JACK VYAS', 'BSF')
INTO EMPLOYEE VALUES ('SEC_14', 'BOL_1', 'BOBBY DUTTA', 'KP FORCE')
INTO EMPLOYEE VALUES ('SEC_15', 'BOL_2', 'VIVEK MISHRA', 'Z PLUS')
INTO EMPLOYEE VALUES ('SEC_16', 'RAM_1', 'ABHISHEK KUMARI', 'BLACK CATS')
SELECT * FROM DUAL;


SELECT * FROM VOTER;

INSERT ALL
INTO CANDIDATE VALUES ('WB_C7','WB_V7','CPM','WB2_1')
INTO CANDIDATE VALUES ('WB_C8','WB_V8','CPM','WB2_2')
INTO CANDIDATE VALUES ('WB_C9','WB_V9','CPM','WB2_1')
SELECT * FROM DUAL;